# Generated by Django 4.0.4 on 2022-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isEmailValid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
