# Generated by Django 4.0.4 on 2022-06-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_isemailvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailValidationUUID',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
