# Generated by Django 4.0.5 on 2022-06-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.BooleanField(default=True),
        ),
    ]
